#!/bin/bash

set -o errexit
set -o nounset

# In docker this file will run from the root directory
# No watchfiles in production
# exec watchfiles celery.__main__.main \
#     --args \
#     "-A authors_api.celery -b \"${CELERY_BROKER}\" flower --basic_auth=\"${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}\""

worker_ready(){
  celery -A authors_api.celery inspect ping
}

until worker_ready; do

>&2 echo 'Celery workers not available :-('

sleep 1 

done

>&2 echo 'Celery workers are available and ready!...:-)'

exec celery \
  -A authors_api.celery \
  -b "${CELERY_BROKER}" \
  flower \
  --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"