#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# python manage.py migrate --no-input
# python manage.py collectstatic --no-input
# exec python manage.py runserver 0.0.0.0:8000

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate

exec /usr/local/bin/gunicorn authors_api.wsgi --bind 0.0.0.0:1998 --chdir=/app