#!/bin/bash

set -o errexit
set -o nounset

# In docker this file will run from the root directory
exec watchfiles celery.__main__.main \
    --args \
    "-A authors_api.celery -b \"${CELERY_BROKER}\" flower --basic_auth=\"${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}\""