#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

working_dir="$(dirname ${0})" # $() for running commands inside. ${} for variables

#source command is used to read and execute commands from a bash file
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

#Bringing in the message_welcome() function from the /_sourced/messages.sh
message_welcome "These are the backups you have got"

ls -lht "${BACKUP_DIR_PATH}"  # -lth => l=long format h=shows size t=sorts by time
